### ISSUE TITLE
Task: Creating integration/systems tests (Wiremock, Pact...)

### ISSUE THREAD

**Issue by youngTickles** [BME-MIT-IET/eng1-iet-2019#5]
making 2-3 integration tests

**Comment by HardPocketRocket** [comment]
Test 1: Testing the add/subtract function and the calendar function together

**Comment by HardPocketRocket** [comment]
Test 2: Testing the startof/endOf and fromNow function

**Comment by ninosmr** [comment]
Test 3: testing humanize function on 24 hours -> 1 day and 60 minutes -> 1 hour

**Comment by ninosmr** [comment]
Test 4: Testing toISOString function, for 24 hours and 60 minutes

**Comment by ninosmr** [comment]
Test 5: Testing locale function working with humanize, to give 1 day in Spanish and French, as well as 1 hour in Spanish and French

**Comment by ninosmr** [comment]
Test 6: Testing conversion of duration parameters, converting 24 hours to 1440 minutes and 60 minutes as 1 hour
